#/daemon/letter.c
__Letter "Error in object: /d/areas/dwarf_mine/mon/goblin#341858 (Tue Jun 15 16:50:00 2021)> *Bad argument 1 to call_other()Expected: string or array or object Got: 0.File: /std/living/combat.c           line 705Traceback-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=1:   heart_beat() in /d/areas/dwarf_mine/mon/goblin#341858Program: /std/monster.cFile:               /std/monster.c line 1312:   continue_attack() in /d/areas/dwarf_mine/mon/goblin#341858Program: /std/living/combat.cFile:         /std/living/combat.c line 3043:   execute_attack() in /d/areas/dwarf_mine/mon/goblin#341858Program: /std/living/combat.cFile:         /std/living/combat.c line 6554:   do_criticals() in /d/areas/dwarf_mine/mon/goblin#341858Program: /std/living/combat.cFile:         /std/living/combat.c line 705"
__Undeleted ({"exash",})
